name: xUnit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Restore dependencies
      run: msbuild /t:Restore /p:Configuration=Release

    - name: Build
      run: |
        msbuild Auto-Layers-SCR.Tests/Auto-Layers-SCR.Tests.csproj `
                /p:Configuration=Release `
                /p:Platform=x64 `
                /p:AppxBundle=Never

    - name: Run tests
      run: |
        dotnet test Auto-Layers-SCR.Tests/Auto-Layers-SCR.Tests.csproj `
                    --configuration Release `
                    --no-build
